### ISSUE TITLE
Ajout Repository Adresse

### ISSUE THREAD

**Issue by chinjto** [takoyadev/takoya-car#16]
En se basant sur l'entité Address et sur le repo CarRepository, créer un repo AddressRepository

**Comment by s6raphin** [comment]
Repo créé :
package fr.takoyadev.car.server.dao;

import org.apache.tomcat.jni.Address;
import org.springframework.data.repository.CrudRepository;

/**
 * TODO description
 *
 * @author s6raphin
 * @version 1.0
 */
public interface AddressRepository extends CrudRepository<Address, Long> {

}

Ton avis ?

**Comment by chinjto** [comment]
t'as pas le bon import, t'as pris ```org.apache.tomcat.jni.Address``` au lieu de ```fr.takoyadev.car.server.entity.Address``` (je l'écrit de tête, vérifie que c'est bien ça)

**Comment by s6raphin** [comment]
je me suis trompé la dedans ?
takoya-car/back/src/main/java/fr/takoyadev/car/server/entity/Address.java
